#iam mock-sdk config
sdk_check_iso_timestamp_format=true
mosip.role.biosdk.getservicestatus=REGISTRATION_PROCESSOR
biosdk_bioapi_impl=nprime.sdk.BiometricAPI



#vendor sdk

mosip.biometric.sdk.providers.finger.mockvendor.classname=nprime.sdk.BiometricAPI
#mosip.biometric.sdk.providers.finger.mockvendor.version=0.9 
#mosip.biometric.sdk.providers.finger.mockvendor.args=
mosip.biometric.sdk.providers.finger.mockvendor.threshold=60
mosip.biometric.sdk.providers.iris.mockvendor.classname=nprime.sdk.BiometricAPI
#mosip.biometric.sdk.providers.iris.mockvendor.version=0.9
#mosip.biometric.sdk.providers.iris.mockvendor.args=
mosip.biometric.sdk.providers.iris.mockvendor.threshold=60
mosip.biometric.sdk.providers.face.mockvendor.classname=nprime.sdk.BiometricAPI
#mosip.biometric.sdk.providers.face.mockvendor.version=0.9
#mosip.biometric.sdk.providers.face.mockvendor.args=
mosip.biometric.sdk.providers.face.mockvendor.threshold=60


logging.level.root=INFO

mosip.biosdk.log-request-response-enabled=false
# Uncomment below when mosip.biosdk.log-request-response-enabled is set to true.
#logging.level.io.mosip.biosdk.services.impl.spec_1_0.BioSdkServiceProviderImpl_V_1_0=DEBUG

#iam image-compressor config
mosip.bio.image.compressor.resize.factor.fx=0.25
mosip.bio.image.compressor.resize.factor.fy=0.25
mosip.bio.image.compressor.compression.ratio=50
